CREATE DATABASE IF NOT EXISTS COLLEGE;
USE COLLEGE;
CREATE TABLE IF NOT EXISTS STUDENT36(
ROLLNO INT PRIMARY KEY,
NAME VARCHAR(50),
MARKS INT,
GRADE VARCHAR(1),
CITY VARCHAR(20)
);
INSERT INTO STUDENT36
(ROLLNO, NAME , MARKS, GRADE,CITY)
VALUES
(101,"KARAN",78,"C","PUNE"),
(102,"ROHAN",93,"A","MUMBAI"),
(103,"RICK",85,"B","DELHI"),
(104,"RAJ",95,"A","DELHI"),
(105,"DHRUV",12,"F","DELHI"),
(106,"FARAH",82,"B","DELHI");
SELECT * FROM STUDENT36;
SELECT * FROM STUDENT36 WHERE MARKS>=80;
SELECT * FROM STUDENT36 WHERE CITY="DELHI" AND MARKS >=80;
SELECT CITY,AVG(MARKS)
FROM STUDENT36 
GROUP BY CITY
ORDER BY AVG(MARKS) DESC;