CREATE DATABASE CHUMKICOSMETICSSTORE;
USE CHUMKICOSMETICSSTORE;
CREATE TABLE PAYMENT(
CUSTOMER_ID INT PRIMARY KEY,
CUSTOMER VARCHAR(20),
MODE VARCHAR(20),
CITY VARCHAR(20)
);
INSERT INTO PAYMENT 
(CUSTOMER_ID,CUSTOMER,MODE,CITY)
VALUES
(101,"OLIVIA BARRETT","NETBANKING","POTLAND"),
(102,"ETHAN SINCLAIR","CREDIT CARD","MIAMI"),
(103,"MAYA","CREDIT CARD","SEATTLE"),
(104,"LIAM","NETBANKING","DENVER");
SELECT * FROM PAYMENT;
SELECT MODE,COUNT(CUSTOMER)
FROM PAYMENT
GROUP BY MODE;

